// Profiles.js
const profiles = [
  {
    studentId: "1", // This is me
    firstName: "Stephen",
    lastName: "Garner",
    country: "United States",
    bio: "This is my profile!",
  },
  {
    studentId: "2",
    firstName: "Mateo",
    lastName: "Maas",
    country: "Argentina",
    bio: "Language enthusiast who loves to learn!",
  },
  {
    studentId: "3",
    firstName: "Edgar",
    lastName: "Gonzalez",
    country: "Paraguay",
    bio: "Passionate about exploring cultures.",
  },
  {
    studentId: "4",
    firstName: "Paul",
    lastName: "Velandia",
    country: "Venezuela",
    bio: "I enjoy meeting new people through language.",
  },
  {
    studentId: "5",
    firstName: "Sofia",
    lastName: "Ramirez",
    country: "Colombia",
    bio: "Learning languages is my passion!",
  },
  {
    studentId: "6",
    firstName: "Alejandro",
    lastName: "Torres",
    country: "Chile",
    bio: "Looking forward to sharing knowledge.",
  },
  {
    studentId: "7",
    firstName: "Isabella",
    lastName: "Cruz",
    country: "Peru",
    bio: "Excited to connect with new people.",
  },
  {
    studentId: "8",
    firstName: "Javier",
    lastName: "Mendoza",
    country: "Ecuador",
    bio: "I love practicing and teaching languages.",
  },
  {
    studentId: "9",
    firstName: "Gabriela",
    lastName: "Flores",
    country: "Panama",
    bio: "Avid language learner and cultural explorer.",
  },
  {
    studentId: "10",
    firstName: "Carlos",
    lastName: "Diaz",
    country: "Uruguay",
    bio: "Always curious and ready to learn!",
  },
  {
    studentId: "11",
    firstName: "Luis",
    lastName: "Morales",
    country: "Mexico",
    bio: "Always up for a friendly conversation!",
  },
  {
    studentId: "12",
    firstName: "Maria",
    lastName: "Lopez",
    country: "El Salvador",
    bio: "Excited to learn more about languages.",
  },
  {
    studentId: "13",
    firstName: "Diego",
    lastName: "Hernandez",
    country: "Guatemala",
    bio: "Sharing cultural experiences through language.",
  },
  {
    studentId: "14",
    firstName: "Lucia",
    lastName: "Martinez",
    country: "Honduras",
    bio: "Always open to new challenges.",
  },
  {
    studentId: "15",
    firstName: "Emilio",
    lastName: "Fernandez",
    country: "Cuba",
    bio: "Language learning is my greatest passion.",
  },
  {
    studentId: "16",
    firstName: "Valeria",
    lastName: "Gomez",
    country: "Bolivia",
    bio: "Enthusiastic about connecting with people.",
  },
  {
    studentId: "17",
    firstName: "Sebastian",
    lastName: "Reyes",
    country: "Costa Rica",
    bio: "Exploring cultures through conversations.",
  },
  {
    studentId: "18",
    firstName: "Ana",
    lastName: "Castro",
    country: "Nicaragua",
    bio: "Excited to exchange knowledge.",
  },
  {
    studentId: "19",
    firstName: "Victor",
    lastName: "Sanchez",
    country: "Dominican Republic",
    bio: "Lifelong learner of languages.",
  },
  {
    studentId: "20",
    firstName: "Camila",
    lastName: "Ortiz",
    country: "Puerto Rico",
    bio: "Language enthusiast and cultural explorer.",
  },
  {
    studentId: "21",
    firstName: "Juan",
    lastName: "Perez",
    country: "Mexico",
    bio: "Excited to connect with learners worldwide.",
  },
  {
    studentId: "22",
    firstName: "Fernanda",
    lastName: "Mejia",
    country: "Chile",
    bio: "Learning one word at a time!",
  },
  {
    studentId: "23",
    firstName: "Nicolas",
    lastName: "Bravo",
    country: "Argentina",
    bio: "Sharing languages and stories.",
  },
  {
    studentId: "24",
    firstName: "Mariana",
    lastName: "Fuentes",
    country: "Colombia",
    bio: "Let's learn and grow together!",
  },
  {
    studentId: "25",
    firstName: "Ricardo",
    lastName: "Vega",
    country: "Peru",
    bio: "Curious about different cultures.",
  },
  {
    studentId: "26",
    firstName: "Daniela",
    lastName: "Paredes",
    country: "Ecuador",
    bio: "Passionate about languages and people.",
  },
  {
    studentId: "27",
    firstName: "Esteban",
    lastName: "Alvarez",
    country: "Guatemala",
    bio: "Let's connect through language!",
  },
  {
    studentId: "28",
    firstName: "Carolina",
    lastName: "Navarro",
    country: "Panama",
    bio: "Language learning makes me happy!",
  },
  {
    studentId: "29",
    firstName: "Andres",
    lastName: "Lopez",
    country: "Uruguay",
    bio: "Learning languages to expand my horizons.",
  },
  {
    studentId: "30",
    firstName: "Paula",
    lastName: "Rojas",
    country: "Bolivia",
    bio: "Connecting with people through language.",
  },
];

export default profiles;
